version: '3.8'
services:
  app:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: torrent
    networks:
      - media_net
      - traefik_proxy
      - default
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Seoul
      - WEBUI_PORT=8080
    volumes:
      - ./.docker/qbit/config:/config
      - ./.docker/qbit/opt:/opt
      - ../media/INBOX:/downloads
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.torrent.entrypoints=https
      - traefik.http.routers.torrent.rule=Host(`torrent.media.hyeon.pro`)
      - traefik.http.routers.torrent.tls.certresolver=leresolver
      - traefik.http.services.torrent.loadbalancer.server.port=8080

########################### NETWORKS
networks:
  media_net:
    external: true
  traefik_proxy:
    external: true
